challenge = ' 30 Days Of JavaScript'
console.log(challenge);
console.log(challenge.length);
console.log(challenge.toUpperCase());
console.log(challenge.toLowerCase());
console.log(challenge.substr(1, 8));
console.log(challenge.substr(3, -1));
console.log(challenge.includes("Script"));
console.log(challenge.split());
console.log(challenge.split(" "));
console.log('Facebook, Google, Microsoft, Apple, IBM, Oracle, Amazon'.split(","));
console.log(challenge.replace("Script", "Python"));
console.log(challenge.charAt(15));
console.log(challenge.charCodeAt(challenge.indexOf("J")));
console.log(challenge.indexOf("a"));
console.log(challenge.lastIndexOf("a"));
let sentence = 'You cannot end a sentence with because because because is a conjunction';
console.log(sentence.indexOf("because"));
console.log(sentence.lastIndexOf("because"));
console.log(sentence.search("because"));
console.log(challenge.trim());
console.log(challenge.startsWith("30"));
console.log(challenge.endsWith("Script"));
console.log(challenge.match(/a/g));
console.log("".concat('30 Days of', 'JavaScript'));
console.log(challenge.repeat(2));